### ISSUE TITLE
Adding the theme's zip file doens't work on Ghost 0.11.2

### ISSUE THREAD

**Issue by ric2b** [dlecina/StayPuft#19]
I really like the look of the theme, congratulations!
It would be really nice, however, if I could simply add the zip file to Ghost's configuration page like with most other themes. I've tried it both with zipping the repo and using the zip from the latest release.

**Comment by dlecina** [comment]
That seems to be a newer feature in Ghost, which has had quite a few updates since my last theme release. I will look into it for the next one. Thanks!

**Comment by dlecina** [comment]
I have uploaded a new version of the theme which supports this method of installation, as long as you carefully  follow the [instructions](https://github.com/dlecina/StayPuft#installation).

In particular, make sure you rename and customize the examples in the `partials` folder. Ghost will not let you upload the theme otherwise.
